### ISSUE TITLE
invalid 'instanceof' operand DS.default.JSONAPIAdapter

### ISSUE THREAD

**Issue by GCorbel** [danielspaniel/ember-data-factory-guy#110]
Hi,

I'm new with ember and FactoryGuy. I have this model (in coffee script) : 

    export default DS.Model.extend
      name: DS.attr('string')
      description: DS.attr('string')
      link: DS.attr('string')
      acquired_skills: DS.hasMany('users', async: true, inverse: 'acquired_skills')
      searched_skills: DS.hasMany('users', async: true, inverse: 'searched_skills')

This factory : 

    import FactoryGuy from 'ember-data-factory-guy';

    FactoryGuy.define('skill', {
      default: {
        name: 'Ember',
        description: 'JSFramework'
      }
    });

And I use it in this test : 

    import Ember from 'ember';
    import { module, test } from 'qunit';
    import startApp from 'social-learning/tests/helpers/start-app';
    import FactoryGuy, { make, build } from 'ember-data-factory-guy';

    var application;

    module('Acceptance | skill page show users', {
      beforeEach: function() {
        application = startApp();
      },

      afterEach: function() {
        Ember.run(application, 'destroy');
      }
    });

    test('visiting /skill-page-show-users', function(assert) {
      var skill = FactoryGuy.build('skill');
      visit('/skills/1');

      andThen(function() {
        assert.equal(true, true);
      });
    });

The test fail when I use FactoryGuy. I have this error message : 

    Died on test #1 @http://localhost:7357/assets/social-learning.js:4468:3
    requireModule/<@http://localhost:7357/assets/vendor.js:150:16
    tryFinally@http://localhost:7357/assets/vendor.js:30:14
    requireModule@http://localhost:7357/assets/vendor.js:148:1
    TestLoader.prototype.require@http://localhost:7357/assets/test-loader.js:29:9
    TestLoader.prototype.loadModules@http://localhost:7357/assets/test-loader.js:21:13
    TestLoader.load@http://localhost:7357/assets/test-loader.js:40:7
    @http://localhost:7357/assets/test-support.js:5485:5
    : invalid 'instanceof' operand DS.default.JSONAPIAdapter@ 47 ms
    Source: 	

    FactoryGuy/this.useJSONAPI@http://localhost:7357/assets/vendor.js:80687:11
    FactoryGuy/this.build@http://localhost:7357/assets/vendor.js:80876:11
    @http://localhost:7357/assets/social-learning.js:4469:17
    Test.prototype.run@http://localhost:7357/assets/test-support.js:3347:14
    run/<@http://localhost:7357/assets/test-support.js:3476:6
    process@http://localhost:7357/assets/test-support.js:3035:4
    begin@http://localhost:7357/assets/test-support.js:3080:2
    resumeProcessing/<@http://localhost:7357/assets/test-support.js:3096:4

The line with the error  is : `var useJSONAPI = (adapter instanceof DS['default'].JSONAPIAdapter);`

Did I made somthing wrong or is it a bug?

thanks!

**Comment by danielspaniel** [comment]
Hmm .. this is quite a nice error .. I kind of like it, since I have not seen it before. Something new and interesting.  Well .. for a starter .. I will make a puzzle for you. First read the documentation and see what you should have written instead of this:

 var skill = FactoryGuy.build('skill');

 that line is not what you should do for this kind of test. There is a sample test in the documentation doing pretty much just what you are doing, so let me know if you can figure it out, and then let me know and I will tell you if you got it right. Now, that might still not fix the error, and you might get the same one, but what the heck, might as well at least start out on the right foot.

**Comment by GCorbel** [comment]
Thanks for the puzzle. I did simply `build('skill')` but the error is not solved. Another clue?

**Comment by danielspaniel** [comment]
Actually that was fine, to build('skill') if you are trying to build something. But the clue here is look for the doc's where it talks about integration/acceptance tests ( look for the word FactoryGuyTestHelper )

**Comment by GCorbel** [comment]
I changer for `TestHelper.handleFindAll('skill', 2);`. `DS['default'].JSONAPIAdapter` is undefined. This is the cause of the error.

**Comment by danielspaniel** [comment]
Yes, that is correct answer (TestHelper.handleFindAll('skill', 2)) .. so that is great that you got that one right.  Now, the next problem is that adapter being undefined .. that is a puzzler. 
 what files do you have in the directory app/adapters ..  if you have nothing there try putting this:

app/adapters/application.js
```javascript
import DS from 'ember-data';
export default DS.JSONAPIAdapter.extend({}); 
```

**Comment by GCorbel** [comment]
Very strange ... I did what you said and it said than it was already included. I removed the code and it works...

I also installed and removed [ember-json-api](https://github.com/kurko/ember-json-api).

**Comment by GCorbel** [comment]
The test does not pass now... I don't understand but I will check it.

**Comment by GCorbel** [comment]
Ok, I added the code you gave and I have this result : `Duplicate default exports`. It seems to be already done.

**Comment by GCorbel** [comment]
This is my `app/adapters/application.js` : 

      export default DS.RESTAdapter.extend({
        host: 'http://localhost:3000',
        namespace: 'api/v1'
      });

I'm using `1.13.1`.

**Comment by danielspaniel** [comment]
Ok .. @GCorbel .. hmm .. well ... I was not sure if you had the adapter .. but you did .. so that rules that out.  It looks like  DS.JSONAPIAdapter is not available.  What happens when you go to browser console (  when your application is loaded ) .. and put this: 

DS.RESTAdapter 
 then 
DS.JSONAPIAdapter

**Comment by GCorbel** [comment]
DS.RESTAdapter 
    >> function makeCtor/Class()
    DS.JSONAPIAdapter
    >> undefined

**Comment by danielspaniel** [comment]
Right .. ok .. that explains that then .. thanks

**Comment by GCorbel** [comment]
I restarted all from scratch. I made a new project with the latest version of ember and I reinstalled  ember-data-factory-guy and it works... So, I close the issue.

Thanks for your very nice help.

**Comment by danielspaniel** [comment]
hooray .. for the 'I reinstalled everything' fix. Thanks for letting me know, and good luck with your factories.
