### ISSUE TITLE
handleFindQuery doesn't make use of query parameters

### ISSUE THREAD

**Issue by mdentremont** [danielspaniel/ember-data-factory-guy#126]
I was trying to setup the following mocks:
- Return [a, b, c] if query parameter X is used
- Return [d, e, f] if query parameter Y is used

Regardless of what I pass in for query parameters to `handleFindQuery`, what ends up getting returned is whatever I passed to the first call of `handleFindQuery`.

Looking at the unit tests for this project, it looks like this would be caused if we setup some "failure" tests. IE: call `handleFindQuery` with query parameter X, and then call `findQuery` with query parameter Y, and assert that our mock was not used.

**Comment by danielspaniel** [comment]
Good find @mdentremont ... I might have to change this method a teeny bit to make this work since ember-data v2.0.0 does not use findQuery anymore, but query and queryRecord.  
Seems like overall I have to clean up a few other methods as well that have changed slightly for v2.0.0 .. I will do that and fix this at the same time .. and let you know when I am done.  
 Might take a few days. So stand by.

**Comment by danielspaniel** [comment]
@mdentremont ... Can you tell me any good reason not to change the api from this:

   ```js  
   testHelper.handleQuery('user', ['name', 'age'], users);
     ```
 To this: 
   ```js
   testHelper.handleQuery('user', {name:'Bob', age: 10}, users);
  ```

For a query like this:

```js
 store.query('user', {name:'Bob', age: 10}});
```

 I am wondering why I ever did the first way ( ['name', 'age'] .. array of query param names ) in the first place, rather than the object of query params that are normally passed in to the query method. 
 
 Anyway .. unless you can think of any good reason to keep the ['name', 'age']  style query args .. I am changing that to object args like ( {name:'Bob', age: 10}} ) 

 and changing handleFindQuery to handleQuery

**Comment by mdentremont** [comment]
@danielspaniel 100% agree, I like the new way better than the array.

**Comment by danielspaniel** [comment]
Yeah, me too .. what was I thinking?

**Comment by mdentremont** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by danielspaniel** [comment]
ok @mdentremont  .. give v1.13.10 a spin, let me know if this fixes things. 
 Note that I changed the api, so you have to now pass in object params not array

**Comment by danielspaniel** [comment]
let me know or open this again if you still have issue
