### ISSUE TITLE
Can't find that factory named ...

### ISSUE THREAD

**Issue by visoft** [danielspaniel/ember-data-factory-guy#142]
I am running Ember-Data 1.13.13 and I upgraded ember-data-factory-guy to 2.1.0. With the new version I get the following message

    Can't find that factory named [<myapp@model:authentication::ember284:4066>]

There is an `authentication` factory in the `tests/factories` directory and was working properly with factory-guy 1.13.2.

Any idea why my factory can't be found anymore?

**Comment by danielspaniel** [comment]
that is a very interesting message.  how are you calling to make or build a model that is causing that error. sounds like a typo where you said make(authentication) instead of make('authentication')

**Comment by visoft** [comment]
import FactoryGuy from 'ember-data-factory-guy;
    ...
    var auth = FactoryGuy.make('authentication');

**Comment by danielspaniel** [comment]
can you dig around a bit and try and trace that one for me and let me know what you find. 
It would be pretty whacky if that was factory guy issue, since this is all factory guy does and the tests are all passing .. but I could be wrong.

**Comment by visoft** [comment]
So I have the following code right after making the factory:

    TestHelper.handleFind(auth);

But it's actually going out to the server (and getting a 404). I'm assuming this is part of the issue.

In my route, I am using `this.store.find('authentication`)` in the `beforeModel` hook. Again, everything was working fine with 1.13.2. 

I tried bumping Ember-Data to 1.13.14, but there's no difference.

**Comment by danielspaniel** [comment]
that is the problem .. I changed handleFind to no longer accept the model form. Check the docs on that one.  if you make the model you should not need handleFind .. right?

**Comment by visoft** [comment]
Awesome, thanks for the fast help. You rock :+1:

**Comment by danielspaniel** [comment]
Don't have your email, but I noticed you wrote article using factory guy .. thanks mucho! :) 
 https://semaphoreci.com/community/tutorials/test-driving-ember-js-components

 Wanted to alert you to latest factory guy upgrade that makes testing even easier/better. I am updating the readme now ( 70% done ) , and will be ready in a few days with new release.  Massive update to acceptance testing and building json.  Hope you can update article to reflect changes, because it's good to have the new stuff out there.
