### ISSUE TITLE
custom adapter?

### ISSUE THREAD

**Issue by xcambar** [danielspaniel/ember-data-factory-guy#150]
Hi,
It doesn't seem possible to transform the JSON that is emitted by Factory Guy. Is it correct?

Our need is fairly simple: Our API doesn't output a format compatible with any of the default adapters.
Most of the time, I don't want to inject data in the sotre during the (acceptance) tests, but rather prepare mockjax to output the JSON corresponding to the generated model _and_ the format of our API.

The adapter we use can transform our format to JSON-API (as required per ember-data 1.13.x), but what we need here is the opposite: transforming the JSON-API payload generated by Fectory Guy to our format.

I don't see any place in the code that seems to allow that (except `findQuery.returnsJSON()`, but that seems a little edgy).

What's your advice for that use case, please?

**Comment by danielspaniel** [comment]
Are you saying .. that:
  You want to convert the JSON-API fixture json to your format .. just so that your adapter can then convert it back to JSON-API .. because your adapter expects a custom format? 

  If so, then you can do this 
 Have a look at the fixture-builder class:

https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/fixture-builder.js

 what this class does is convert the raw fixture built by factory guy to what should be expected for the adapter in question.  I have build converters for JSON API and REST style adapters.

  All you have to do is build your own converter and then make your own fixture builder class for your adapter, and then modify the fixture builder factory to return your custom fixture builder and your ready to go.  It's not that terribly hard.

**Comment by xcambar** [comment]
Sweet! Thank you.

"Not terribly hard", I agree on that, but as you seem to suppose it is obvious, I have to argue it could probably use some documentation (use case seems pretty common).
I'll implement your solution and come up with a PR on the README if you don't mind, for which we could discuss its usefulness later on. :smile: 

Thanks again for the help

**Comment by danielspaniel** [comment]
Actually .. you'de be surprised how many adapters for ember inherit from the RESTAdapter .. which means you don't have to do anything. Which is why I have only heard for this type of request so infrequently ( once before ) 
  I guess the documentation for how the whole fixture building works would be a nice graphic thingy .. which would be fun, but most people don't really want to see it  I reckon.  Luckily, the code base is pettite, and you can kind of follow the gist of things, otherwise I would say .. yeah .. need the diagram. 
 I would be happy to accept a PR for this .. sure thing.

**Comment by xcambar** [comment]
> and then modify the fixture builder factory to return your custom fixture builder

That's the whole problem. The factory is not part of the public API, henceforth can not be extended.
Whatsmore, the `fixtureBuilder` and `fixtureBuilderFactory` are private members of the addon and accessed privately by the methods.

If I missed something, I'm all ears. From my perspective, I can't have the behaviour I'm after without modifying the codebase. Which I'll work on pretty soon.

**Comment by danielspaniel** [comment]
Most 100% definitely true .. your going to have to modify the code base.  Good point though .. would be neat to allow this functionality to be extensible by writing your own builders and pugging them in somehow. I am open to ideas on how to do that.

**Comment by xcambar** [comment]
Closing, as it has been merged. See #152
