### ISSUE TITLE
how to know if mock request was sent?

### ISSUE THREAD

**Issue by jaydev** [danielspaniel/ember-data-factory-guy#186]
I'd like to know if there's a simple way to know if a mock request was triggered or not.

Example:

```js
let isUpdated;

mockUpdate('profile', id).then(function() {
  isUpdated = true;
});

assert.ok(isUpdated);
```

I looked through the docs and the code for `mockUpdate` but I didn't see any way to do this.

**Comment by danielspaniel** [comment]
You bring up a very good point, because usually the word mock implies that you can check if the call was made, but I used that word mock instead of stub ( which is more accurate here ) .. because I am using mockjax library and wanted to sorta consistent .. anyway .. 

but take a look at this:
  http://stackoverflow.com/questions/24924541/how-to-verify-that-mockjax-has-been-called
which will show you how to get that list of mocked calls.

**Comment by danielspaniel** [comment]
I wonder if that is something I could build in to factory guy .. where I can use that info from mockjax to assert that your mock was called .. interesting idea

**Comment by danielspaniel** [comment]
this feature is now in v2.5.1 .. you can find info in the docs 
https://github.com/danielspaniel/ember-data-factory-guy#verify-how-many-times-the-ajax-call-was-mocked

**Comment by danielspaniel** [comment]
Although I realize that I forgot to add this to mockUpdate .. argh .. I will do that later

**Comment by danielspaniel** [comment]
Ok .. now v2.5.2 has the timesCalled on mockUpdate
