### ISSUE TITLE
Proposal - add mockDeleteAny

### ISSUE THREAD

**Issue by mattmcginnis** [danielspaniel/ember-data-factory-guy#201]
Sometimes I have models in the store that get deleted but since they were automatically built using traits, I don't know the ids or have a reference to specific objects.  I can get the ids, but since I'm not testing that they get deleted (for some tests) I'd rather just have mockDeleteAny('model') or just mockDelete('model') that supports deleting any model of that type without needing to specify the id.

I can work on this if it's deemed a good idea.

What do you think Daniel?

**Comment by danielspaniel** [comment]
Hmm .. I reckon .. it's a good idea .. I think the mockDelete('modelType')  would be the easiest because it is already there and all .. if you hook that up I will use it.

**Comment by danielspaniel** [comment]
howdy partner .. are you still into doing this .. ?? 
  I think I might roll it out this weekend  for next week if you don't get to it .. because it is fairly easy now that the code is better looking for the mock requests .. 
  I know this is a long weekend .. so f your not doing anything else .. this is your chance to do it before I do. so let me know :)

**Comment by mattmcginnis** [comment]
Hey Daniel, sorry I won't be able to look at it before next week.

**Comment by danielspaniel** [comment]
No problemo Matt,  Let me know if you want me to save it for you to do them .. otherwise I will finish it.

**Comment by mattmcginnis** [comment]
Maybe you can save it for me since I'm the only one who needs it at the
moment. :)  I'll see if I can squeeze in some time today.

**Comment by danielspaniel** [comment]
Sure thing Matt. 
  It is actually alittle bit tricky ( just a little bit ) 
 because usually a DELETE needs the modelName and id to build the url 
 so all you have to do is to set up a new MockDeleteRequest ( extend from MockRequest ) 
 and then the url to match has to be a regex like /modelName/\d+  or something like that
 but then the problem is that the handler ( the way it is setup now  )
  is just doing a strict match like url === url .. and not matching regex .. but that is about the only two issues and it would be super fun to do it .. 
  soo .. i will leave that alone

**Comment by mattmcginnis** [comment]
https://github.com/danielspaniel/ember-data-factory-guy/pull/207

**Comment by danielspaniel** [comment]
v2.6.4 has this new ability .. :)
