### ISSUE TITLE
meta information getting dropped from json requests.

### ISSUE THREAD

**Issue by sgargan** [danielspaniel/ember-data-factory-guy#267]
I've been trying to use a meta block when building a payload for a json response, but when the response is transmitted the meta block gets stripped away. I saw this line in the [json payload](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/payload/json-payload.js#L10) wondering why this is not working and dug around a little. 

Seems the reason is [this line in mockjax](https://github.com/jakerella/jquery-mockjax/blob/master/src/jquery.mockjax.js#L257), the JSON.stringify call is stripping the meta block. It may be possible to craft a string and pass this as the responseText which would take the `else` path and skip this conversion.

**Comment by danielspaniel** [comment]
Whoa .. it has been way too long since I visited this meta issue .. but glad you did .. so happy to dig in to it again.  

Can you do us both a favor and write a failing test:
 Where you set up your meta info
 and then expect to see it later in payload 
and it fails ( in other words ) 
  
 than we have a basis to stand on and work on. 

The JSON.stringify thing has to happen because its a json payload. The whole payload concept / class is built upon that assumption. . so not sure if that is avoidable.  But .. I could always be wrong about that.

**Comment by danielspaniel** [comment]
Howdy partner, any word on this? I would love to get this fixed / cleared up/ tossed in the dumpster ??  I don't mind helping. If you want to screen share, and show me what is going on I can do the rest.

**Comment by sgargan** [comment]
@danielspaniel I did look a little more into this and like you feared changing it would be major surgery and I've worked around it for now. When I get a minute I will put together a test case to capture the issue.

**Comment by danielspaniel** [comment]
Oooo .. ok .. thanks for the update.  Look forward to seeing if I can figure out what is going on ( and you nice test case as well )

**Comment by danielspaniel** [comment]
Based on @jeobrien test and PR I am closing this issue because meta seems to work pretty well, and I added a test case in user-search-test ( besides the one already in shared behaviour tests for mockQuery ) to prove it

https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/acceptance/user-search-test.js#L86
