### ISSUE TITLE
.add({ meta: not working

### ISSUE THREAD

**Issue by twbrandt** [danielspaniel/ember-data-factory-guy#272]
`buildList` with `.add({ meta:` is not working in phantomjs. For example, in my test I have this line:
```
let peopleJSON = buildList('person', 20).add( {meta: { 'record-count': 30 }});
```
PhantomJS throws this error:
```
http://localhost:7357/assets/test-support.js:6956:22: undefined is not a constructor (evaluating 'Object.assign(this.json.meta, data)')
```

This works fine in Chrome.

I am using ember-data-factory-guy 2.11.3 and phantomjs-prebuild 2.1.13.  I haven't had a chance to dig into this yet, but wondered if anyone had any suggestions for resolving this issue.

**Comment by danielspaniel** [comment]
It is a problem I would have caught because i used to run the tests in phantom on ci, but a version or two of something ( ember / cli / qunit / testem .. ??)  suddenly phantom run would just barf and not find any tests, making it basically unusable. Chrome though was fine for running tests. So I switched.  Sadly then I missed this kind of issue. 
 And I could switch to phantom ( just for this issue ) and try and get to this test and see if I can figure out why it's failing, but give me a few moments.

**Comment by danielspaniel** [comment]
Oh .. yeah .. forgot to say .. in the meantime .. ( and I know you probably already know this ) .. you could switch to run chrome in ci ?? is than an option ..

**Comment by twbrandt** [comment]
Yeah, I've already switch to chrome :) Thanks!
