### ISSUE TITLE
FactoryGuy.make can not distinguish different models named the same.

### ISSUE THREAD

**Issue by phcoliveira** [danielspaniel/ember-data-factory-guy#297]
Hi again!

I was wandering if it wouldn't be better if `FactoryGuy.make` were more like `FactoryGuy.makeList`. Consider the two factories:
```javascript
FactoryGuy.define("foo", {
  default: {},
  commonName: {}
});

FactoryGuy.define("bar", {
  default: {},
  commonName: {}
});
```
By using `FactoryGuy.makeList`, we can specify which factory we want, with the first parameter, while the second serves the purpose of specifying the version of such factory. But `FactoryGuy.make` doesn't work the same way, and expects both a factory type or a named version of all defined factories. This leads to confusion, for it is possible, and somewhat likely, to have two versions from two different factories named the same.

**Comment by phcoliveira** [comment]
Well, it seems that `FactoryGuy.makeList` also can not distinguish two versions named the same from two different factories.

**Comment by danielspaniel** [comment]
can you give me examples of what you are writing about? What you are trying to do or accomplish? I sort of get it. But not really. 

```js

 make( modelName, 'trait' , 'trait2', {key: value});  // make a model
 makeList( modelName, ['trait' , 'trait2', {key: value}] ); // does the same as above except it goes in list

```

 it is true there are differences with make and makeList, but they have to be different because the basic idea is:
```js
make(modelName) // makes one model
makeList(modelName, 3)  // makes 3
```

**Comment by phcoliveira** [comment]
I believe some of the instructions on README are wrong. Let me quote them:
```

**Comment by danielspaniel** [comment]
Boy .. that was a good point. You get a free trip to the cricket ranch and a bowl of crickets just for you! 
 I never thought of that case. 
  I rarely use named types ( traits are more useful ) but not sure what to do here. 

 Maybe the answer is just keep it the way it is and just realize you will get bugs if you use same named type in difference factories??  ( I could add that to that to the docs )

  I would vote for that .. because I don't know what else to do except remove named types completely since they can cause this very issue. 

  Any other suggestions?

**Comment by phcoliveira** [comment]
Well, thanks for the crickets, I guess. I hope I was of some help.

Well, again, I am namespacing my named versions, colons are great. So, it goes like this:

```javascript
FactoryGuy.define("user", {
  default: {},
  "user:handsome": {}
});
```

**Comment by danielspaniel** [comment]
That is really clever idea .. ( to namespace the named version )  thanks for sharing it.  😄
