### ISSUE TITLE
Could not find how to mock JSON:API included data

### ISSUE THREAD

**Issue by MartinMalinda** [danielspaniel/ember-data-factory-guy#306]
Currently, I have an issue, that in test environment, the data are lazy loaded, while in dev/prod they are bundled together via JSON:API `included`. This can cause several things to behave a bit differently in these environments.

Is there any build-in support for returning a model with `included` data? It seems like only `attrs` are supported so far.

**Comment by danielspaniel** [comment]
I think you can do this @MartinMalinda 

use the add method on build 

 => EXAMPLE:

```javascript
 let heros = buildList('hero', 3);
 let comics = build('comic-book').add(heros);

 mockFindRecord('comic-book', 1).returns({json: comics});

 // just for fun, to see the json payload yourself
 comics.unwrap();
 console.log(comics);
 ```

**Comment by MartinMalinda** [comment]
Thanks for the help and sorry for this late response, but only now I found time to get back to this.

I think `add` is what I need, thanks! But I still have some problems.

This is what I do:

```
  const childItemsJson = buildList('child-item', 50);
  const parentJson = build('parent').add(childrenItemsJson);
  mockCreate('parent').returns({
    attrs: parentJson
  });
```

At this point when I debug this, everything seems to be set up correctly. `parentJson` has correct id (`parent-1`) and it has included 50 of childrernItems.

But after putting debugger in `save().then` hook. I can see that the `parent` has id `1` instead of `parent-1` and it has no `childrenItems`. In production/development against a real backend, I have no issues. 

I can confirm that this mock is being used, because if it is removed, I get 404.

Do included data work correctly with `mockCreate` ? Maybe I need newer version of Ember Data? (I'm at 2.7.0 currently)

**Comment by MartinMalinda** [comment]
Okay, I think I've figured it out :) While `.add` will add the included data, it will not set up the relationship. It works now with this approach:

```js
const childItemsJson = buildList('child-item', 50);
const parentJson = build('parent', { childItems: childItemsJson }).add(childrenItemsJson);
```

**Comment by danielspaniel** [comment]
Oh boy, that was a very very good solving of that problem @MartinMalinda .. bravo. 
 I forgot that you would need to set up the relationship of childItems  as well as including them, but that should have been obvious to me.  How would that ever work otherwise?  I think I need to update the docs and my own tests actually, so thanks for getting me thinking.

**Comment by danielspaniel** [comment]
There is an example now in the README -> https://github.com/danielspaniel/ember-data-factory-guy#using-add-method
 for showing your technique for adding a payload that is included and is ALSO related to the model

**Comment by danielspaniel** [comment]
Gosh .. I am a total noodle head. I forgot that build method automatically adds the relationships to the included section of the data  

so your example of 

```javasctipt
const childItemsJson = buildList('child-item', 50);
const parentJson = build('parent', { childItems: childItemsJson }).add(childItemsJson);
```
should have only needed
```javasctipt
const childItemsJson = buildList('child-item', 50);
const parentJson = build('parent', { childItems: childItemsJson });
```
since the childitems will be included automotically as I was saying. 

So, now I completely forgot what the actual issue is ... 😨    

I am going to reopen this so you can let me know if there still is an issue and help me to see it, or close it yourself.

**Comment by MartinMalinda** [comment]
@danielspaniel sorry for the confusion! I'm currently on a different project but I'll try to retest this as soon as I get my hands on it again.

**Comment by danielspaniel** [comment]
ok thanks Martin, I am looking at the adapter options bug ( you filed ) on your repo and that is really puzzling me at the moment.

**Comment by danielspaniel** [comment]
@MartinMalinda ..  I think this issue is getting too vague for me and I need some clarification.  
Let's get back to the basic thing you are trying to do.  
Can you explain it again? 
Is it  a problem with mockCreate and returning relationship data. 
If so, can you clearly show the issue or make a failing test for me?

**Comment by danielspaniel** [comment]
Going to close this due to no response, but please reopen if you still have issue
