### ISSUE TITLE
"build" proxy bug

### ISSUE THREAD

**Issue by Exelord** [danielspaniel/ember-data-factory-guy#330]
Hey :)
According to the docs proxy on objects doesn't work correctly:

```js
build('user').get('firstName') // undefined
build('user').get('first-name') // myName
```

The proxy forgot to camelize the attribute key.

**Comment by danielspaniel** [comment]
Howdy Maciej, you have hit upon a great question. Why the dasherized keys? 
 
  Remember .. the build method gets you a payload 
  a payload is json like this:
 
```json
{ 
    "data": {
       "id": 1, 
       "type": "user",
       "attributes": { "first-name": "blah" }
    }
};
```

The build returns a special project class that can inspect this json .. but since you are building for a payload that is JSONAPI ( in your case ) .. you get dasherized keys. 

 I am going to make a special method called  attributes_for that will do what you really want 

 Example:

 ```js 
  let attrs = attributes_for('user');  //=> { firstName: "blah" }
 ```

 Give me a day to finish that 

Any other questions ?

**Comment by Exelord** [comment]
That's exactly what I wanted to achieve! :)  Great answer Daniel!
I just expected to have `build` method the same as in `FactoryGirl` which returns pure attributes objects.

Is the `attributesFor` method will also return all relationships inside?

**Comment by Exelord** [comment]
Maybe we should keep the consistency with the FactoyGirl and allow `build` to return attributes and have another method like `payloadFor` for returning payloads objetcs?

**Comment by danielspaniel** [comment]
In factory girl ( ruby ) they have a  method called attributes_for . so I was using that idea 

 i am not sure if I can do relationships properly but I can try ? 
 
  in our world of ember data we need payloads to build is perfect for that. 

  i could do 
  
  attributesFor('user')
   OR maybe
  build('user').getAttributes() // new method on build ?? 
    or 
  build('user').get(); // i could fix it to return keys like you expect from a real model ( would be super cool but super hard )

**Comment by Exelord** [comment]
Right, sorry I was wrong :)

I think `attributesFor('user')` would be perfect. The rest `build('user').getAttributes()` `build('user').get()` will be just nice to have :)

having relationships attributes in the object would be sth amazing for me especially for complicated forms tests. But of course, it can be added later on as it will be possible to bypass it using `attributesFor` :)

**Comment by danielspaniel** [comment]
attributesFor is really easy .. so i going to try to do build('user').get() style since that one I use all the time and I get sick of the dasherized keys .. and it going to be really tricky

**Comment by Exelord** [comment]
Im just not sure now if this will be a good approach.
What if the `build` object would contain deserialized attributes object, like `build('user').attributes` and the `get` would be just a proxy on it? but in that case, we would have to move all request payload keys to a container key like `payload`

**Comment by danielspaniel** [comment]
not sure why i would do that?  why do i need attributes key ? 
 I guess I can see why .. but what is wrong with .get() returning the regular keys like a rest payload would ? 
  also I  can not use a property key like attriubutes  

 do you know how this Payload class actually works.  Check it out and let me know if you understand what I talking about. Otherwise I can get on slack and explain it and we can think about a good solution together.

**Comment by Exelord** [comment]
There is nothing wrong. :) The question here is that using `get('camelizeValue')` can be a little confusing when calling on dasherized keys payload. Im just thinking ... when we will have an `attributesFor` method, maybe then, getting attributes form a built payload using get should be considered as a bad pattern as this is not a goal of payload object? Maybe it works perfectly fine right now?

Moreover, we can't override a `get` method as then the `get(payload, 'myKey')` won't be working as well, I think so.

Sure I agree, we should have a way to access attributes hash from the payload object by using some native getter property `build('user').attributes` or a function `build('user').getAttributes()`.

So theoretically we can solve 2 problems at once :) Let's say we have an `attributesFor` for getting object of attributes and `build('user').attributes` where we can `get()` on it with dasherized key :)

> do you know how this Payload class actually works. Check it out and let me know if you understand what I talking about. Otherwise, I can get on slack and explain it and we can think about a good solution together.

I will look at it through the weekend, but if you would like to chat or talk about it, I'm always open to do it :)

**Comment by danielspaniel** [comment]
Whooray Maciej .. you make some very very good ideas 🏅 
  You're right .. build should be for payload  and to use that for attributes is just confusing ( and is a bad pattern as you say ) 

 It should be its own method to do just that one thing that it is supposed to do ( get attributes for model ) 
 
 please check out that JsonPayload class , because we can not put any keys on that json build payload and only we can put functions => I will leave this as a special puzzle for you to figure out why.  If you can solve the riddle you will earn the  💎

**Comment by danielspaniel** [comment]
I just finished that .. so now we have attributesFor .. whooray .. thanks for discussion 
=>  v2.13.27
