### ISSUE TITLE
Unable to re-mock

### ISSUE THREAD

**Issue by Exelord** [danielspaniel/ember-data-factory-guy#331]
Hey @danielspaniel  :)
Sorry for bothering you once again, but, could you verify if this is a bug or expected behavior?

```js
let errors422 = { errors: { firstName: 'Name too long' } };
mockUpdate('user').fails({ status: 422, response: errors422 });
user.save() // Fails as expected

mockUpdate('user')
user.save() // Fails again but it was remocked to success :/
```

**Comment by danielspaniel** [comment]
Not sure what supposed to happen there Maciej.  Are you trying to mock fail and then mock success? or you want to keep failing? 
 If you want what I think you want ( fail , then succeed ) then do this
 
```js
let errors422 = { errors: { firstName: 'Name too long' } };
let mock = mockUpdate('user').fails({ status: 422, response: errors422 });
user.save() // Fails as expected

mock.succeeds() 
user.save() // will now succeed
``` 
and it's no trouble .. i don't mind answering

**Comment by Exelord** [comment]
Yes, I expect to be able re-mock it to success.
```js
mock.succeeds() 
```

Pretty cool :) Thank you!
But anyway, in my opinion, more intuitive way do it would to just overwrite it. But it's not a problem anymore, so thanks once again! 
Cheers 🍻

**Comment by danielspaniel** [comment]
Well, you make a good point too Maciej. 

  mockUpdate('user').fails() 
  mockUpdate('user') 
 
  kind of assumes now mockUpdate succeeds because last one wins. 
 right now, I don't bother to check if there already is a PUT /users  being mocked, and 
 just add the new one, which means the FIRST one always wins since the search is from first to last. 
  is that reasonable .. in this case no. should be last to first. 
  are there cases where that does NOT work though. 
  Think about it. 
  If you can make the case where the last mock should always win then I will change it so it works like you expect ( because I think others will expect same )
