### ISSUE TITLE
mockCreate making two records unexpectedly

### ISSUE THREAD

**Issue by geekygrappler** [danielspaniel/ember-data-factory-guy#350]
Hi, I'm not sure if this is a bug, but it was unexpected. In a test where we expect a call to `POST` `/foos` I am trying to use `mockCreate` and it's giving back a resource with an ID of 2 instead of 1.

```
  test('using mockCreate with makeNew does not works', async function(assert) {
    let foo = makeNew('foo');
    mockCreate(foo);
    await visit('/');

    assert.equal(currentURL(), '/foo/1', 'We are only making one foo, so the id should be 1');
  });
```

It works with `mockCreate('foo')` but not `mockCreate(foo)` either with `makeNew` or with `make`. I'm not sure if this is a bug or if I'm missing where the first `foo` is being created and why the handler is returning a `foo` with id `2`.

I made a repo with some tests: https://github.com/geekygrappler/edfg-bug

Thanks,

Andy

**Comment by danielspaniel** [comment]
good question Andy.
and before I find out why there are 2 being made, you should do this instead:

```js
  test('using mockCreate with makeNew does not works', async function(assert) {
    let foo = makeNew('foo');
    mockCreate(foo);
    await visit('/');

    assert.equal(currentURL(), `/foo/${foo.id}`, 'We should not really care what the id is, even if FG is working overtime to make 2, and this is a silly thing to do, which you are right about');
  });
```
 You might say, but Dan, we all know there is only 1 foo being made, and FG is making 2, and you are spot on with that one.  Even before I fix that, you should never assume what the id is going to be in a test like that, because even in real server to client life, the server returned id could be anything , even a uuid.

**Comment by danielspaniel** [comment]
so my answer was accurate, and to explain further, the reason the id is 2 is because the first makeNew uses id 1 but that id is thrown away after the fixture is made.  So you could say the id 1 is wasted but I don't particularly mind, nice it is just a number that no one cares about in general so long as it is uniq for a model type. 
 Then for the mockCreate, it gets the next id which is 2. 

So the way I explained to make the test above is accurate. Any other questions, please feel free to ask them.

**Comment by danielspaniel** [comment]
You're problem is here:
```js
export default Route.extend({
  async setupController() {
    let foo = await this.store.createRecord('foo').save();
    this.transitionTo('foo.show', foo);
  }
});
```
this should be 
```
export default Route.extend({
  model() {
    return this.store.findRecord('foo', params.foo_id)
  }
});
```
what you are doing is so contrived that i don't even understand it. 
 
Is your route a valid use case ?  Is that the way your real route is being used? 
 If so then the way to make this pass is then to do this: 

```js
  test("id for new record created AND saved in route", async function(assert) {
   // no point makeNew or make here because  the model is being made in the route ? which puzzles me
    mockCreate('foo');
    await page.visit();
    assert.equal(currentURL(), 'foo/1');
   // you could get the foo like this FactoryGuy.store.peekRecord('foo'. 1); 
  });
```
 OR 

```js
  test("id for new record created AND saved in route", async function(assert) {
   // no point makeNew or make here because  the model is being made in the route ? which puzzles me
    mockCreate('foo').returns({attrs: {id: 3}});
    await page.visit();
    assert.equal(currentURL(), 'foo/3');
   // you could get the foo like this FactoryGuy.store.peekRecord('foo'. 3); 
  });
```

since you are creating and saving the model in the route itself, which I have never seen before. 
 not sure if you are making a real life example, but let me know if you are and i can guide you further. 
 The way you were originally doing this was not a bug ( failing test ) was just not really following the way the route was working ( if you follow what i am saying )

**Comment by geekygrappler** [comment]
Hmmm very sorry. I've made the example exactly how I want the app to behave, rather than a contrived example. Maybe there is something off in my pattern. I simply want to take some form data and create a model with it. 

So I have a form with say one input field for `bar` on the template and then I have an action when that is submitted which creates and saves the record and then transitions to it.

template
```
<form onsubmit={{action 'createFoo'}}>
  {{input type="text" value=fooData.bar}}
  <button type="submit">Save</button>
</form>
```

controller:
```
import Controller from '@ember/controller';
import { inject as service } from '@ember/service';

export default Controller.extend({
  store: service(),
  actions: {
    createFoo(e) {
      e.preventDefault();
      let foo = this.store.createRecord('foo', this.fooData);
      foo.save().then(foo => this.transitionToRoute('foo.show', foo))
    }
  }
});
```

The route simply sets up `fooData` as an object in `setupController`. So I think the test is now correct?
```
  test('using mockCreate with make also does not work even using foo\'s id', async function(assert) {
    let foo = make('foo');
    mockCreate(foo);
    await visit('/');

    await fillIn('input', 'Andy');
    await click('button');

    assert.equal(currentURL(), `/foo/${foo.id}`, 'We are only making one foo, so the id should be 1');
  });
```
So the flow should be land on `/`, fill in the form with some data, the action on submit should create a record in ED with the data, ED should then try and save the record with the API, the API should return a persisted record with an ID of 1. Is my pattern wrong?

**Comment by danielspaniel** [comment]
ok .. i see your point now Andy, thanks for extra explaining it. 
  Your test would be better like this: 

```js
  test('using mockCreate with make also does not work even using foo\'s id', async function(assert) {
    mockCreate('foo')
    await visit('/');

    await fillIn('input', 'Andy');
    await click('button');

    assert.equal(currentURL(), `/foo/1`, 'You are now only making 1 foo, so the id should be 1');
  });
```

do you not love this?  I do .. so simple .. so easy .. too easy perhaps?

**Comment by geekygrappler** [comment]
Haha, yeah OK. I will just stick with that. Thanks Dan.
