### ISSUE TITLE
Ember Data version constraint

### ISSUE THREAD

**Issue by grantovich** [danielspaniel/ember-data-factory-guy#51]
Factory Guy currently locks Ember Data to 1.0.0-beta.12 exactly – current version is 1.0.0-beta.14.1. Any chance this constraint could be relaxed? I did a quick run of the Factory Guy test suite against the new version and had only one failure, something to do with the fixture adapter, though I'm not sure how to approach fixing that since I'm very new to Ember.

**Comment by danielspaniel** [comment]
Do you want me to make new version for 1.0.0-beta.14.1 ? 
 I tried it and the tests passed like you said except for one. 
But I was going to ignore this beta release ( and wait for 1.0.0-beta.15 )  since there are so many bugs for me to even use that version. I switched to it (1.0.0-beta.14.1 ) in my Ember related project and there were a few hasMany related bugs that made it unusable ( so I reverted to 1.0.0-beta.12).
 I checked the issues for ember-data and they are working on them.  So by 1.0.0-beta.15, they should be fixed. ( hopefully )

**Comment by grantovich** [comment]
Ah, okay. We are not in a big rush to upgrade, I was just wondering why the version constraint was in place. Thanks for clarifying that!

**Comment by danielspaniel** [comment]
I have to do a version constraint because I often ( but not always ) have to change the FactoryGuy code to make it work with the new version ( especially starting with 1.0.0.beta.8 and up ). Every new version was breaking things, so I locking in a version number for a tag version so you could at least know that the FactoryGuy code would work for whatever version you were using.

**Comment by grantovich** [comment]
Yep, I understand it now – this can be closed if you want. Or maybe leave it open so that others know you are waiting on the 1.0.0-beta.15 release before upgrading.

**Comment by danielspaniel** [comment]
Maybe I will put something in readme actually .. easier to find. Good idea though.
