### ISSUE TITLE
.reload()

### ISSUE THREAD

**Issue by yratanov** [danielspaniel/ember-data-factory-guy#54]
Calling ```.reload()``` causes weird request: ```GET http://localhost:7357/companies/1/tests/index.html 404 (Not Found)```.

**Comment by danielspaniel** [comment]
Hmm .. that is kind of an odd url for a reload. What is the context for this? Can you recreate this somehow in a test? ( I am guessing not? ) .. Maybe by using a mock like:
 factoryGuy.testMixin.stubEndpointForHttpRequest( '/companies/1', {id:1})
 will do the trick? Since, if in your application calling .reload on a model needs to be mocked .. and I am guessing (hoping) the url your getting is throwing you off and just letting you know ( hey, please mock the reload url .. even though the url I am showing you is stupid )

**Comment by yratanov** [comment]
I expected that if I have 
```coffee
    company = factoryGuyHelper().make('company')
```

Then when the company is reloaded in the app it will not do a request. But it seems I need to do 
something like this:
```coffee
factoryGuyHelper().handleFindOne('company', id: 1)
```

**Comment by danielspaniel** [comment]
Only problem with the handleFindOne is that is makes the record, so it's not good for just handling reload. Unless you use it for making and then also handling reload ( if you know what I mean ) ..

**Comment by Marthyn** [comment]
Yeah, i thought of that too, you should be able to pass the object you want to return too, (you can of course pass all attributes and have the same result)

**Comment by yratanov** [comment]
@Marthyn :+1:

**Comment by danielspaniel** [comment]
@yratanov , @Marthyn,  I added ability to handle reload in handleFindOne , because you can now pass in an existing record. Check it out in v0.9.5 and let me know what you think. 

 Also, I hope you don't get too upset, but I deprecated handleFindOne in favor of just handleFind
I did same for handleFindMany to handleFindAll  because the names now match what ember data is doing with store.find or store.findAll

**Comment by yratanov** [comment]
@danielspaniel Thank you :+1:

**Comment by Marthyn** [comment]
Oh this is much better! Awesome!
