### ISSUE TITLE
Issue when using handleUpdate

### ISSUE THREAD

**Issue by pedrokiefer** [danielspaniel/ember-data-factory-guy#60]
I'm writing some tests using handleUpdate, but it keeps failing. I think it's because factory-guy returns an empty set on PUT requests. 

The error message is the following:
"An adapter cannot assign a new id to a record that already has an id. <my-app@model:mymodel::ember882:1> had id: 1 and you tried to update it with null. This likely happened because your server returned data in response to a find or update that had a different id than the one you sent."

In this project I'm using ember-data-tastypie-adapter, ember 1.9.1 and ember-data beta.14. Maybe returning the id would solve, or serializing the hole object, not sure though. Maybe this specific for this adapter, or related to beta.14.

**Comment by danielspaniel** [comment]
True, @pedrokiefer  about the return of empty for PUT's.  I put a notice on the README saying I was having problems with the beta.14.1 release and was going to wait for beta.15 to come out to see if that was better ( whacky issues that seemed ember data related ) .. so my question is, can you revert to ember-data beta.12 for now ( that is what I am doing ) .. and it should  be fine.

**Comment by pedrokiefer** [comment]
@danielspaniel sure I can. It's just hard to keep up with ember folks, there is always a new release and lots of new features. I haven't read the changelog for what is going on on beta.15, so I can't comment if this issue will go away. 

My idea to solve this issues was to serialize the object and return it. The problem is, we need to serialize it just before returning the data and not on handleUpdate registration, or else the update will return the old object data.

**Comment by danielspaniel** [comment]
Exactly @pedrokiefer ... not so simple .. and in the ember beta.12 release returning empty is the standard  when nothing changes except the updates you made, so that strategy was pretty good. 
 For the next beta release I will have to adjust and as you say .. I may have to do something tricky to get that to work ..  not sure yet though, but in the next few weeks when that is released I will try and fix it.

**Comment by pedrokiefer** [comment]
I was reading mockjax docs, and it accepts a function for response and calls it before returning data. So we can have something like:

```
function create_response_callback(modelName, record, mapping) {
    return function (settings) {
        var json = record.toJSON({includeId: true});
        var responseJson = mapping(modelName, json);
        this.responseText = responseJson;
    }
}
```

Where modelName is the model name, record is the record being updated and mapping is ```FactoryGuyTestMixin.mapFind``` function. 

```stubEndpointForHttpRequest``` would need to accept a the result of this function and set mockjax options to use this function.

What do you think about that? I can try and make a PR if this works as expected.

**Comment by danielspaniel** [comment]
It's true about the function .. and it just might work to do something like this @pedrokiefer. 
Take a look at the handleCreate method. It's using a function to check the data.  
 I think you could do same kind of thing to accomplish this for handleUpdate ( check request data and set response data ). 
 If you do make a pull request, make sure to add a test or two that fail without this new functionality you are adding ( if you know what I mean )

**Comment by danielspaniel** [comment]
Closing this one since releasing new version 0.9.10 with you new code I just pulled in.

**Comment by danielspaniel** [comment]
@pedrokiefer,  I am reworking the was factory guy handles buiding json, so return properly formated json that is ready to be send to adapter ( see issue #113 ) 
 This means that the mapFind method might be out of the loop is building ( unless I can figure out how to bring it back in ). 
 
 This means that now the handleFind method will no longer have to make the build and then call mapFind as it does now, since the json returned will already be setup with modelName preset:

 ```js
  handleFind: function () {
    var args = Array.prototype.slice.call(arguments);
    var modelName = args.shift();
    var json = FactoryGuy.build.apply(FactoryGuy, arguments);
    var id;

    if (FactoryGuy.useJSONAPI()) {
      id = json.data.id
    } else {
      id = json.id;
      json = this.mapFind(modelName, json);
    }

    var url = this.buildURL(modelName, id);
    new MockGetRequest(url, modelName, json);
    return id;
  },
```

What will happen now is that the build funciton will produce this:

```js
  var json = build('user', 'with_hats');

  // json ->
  {
    user: {
      id: 1,
      name: 'User1',
      hats: [{type: 'big_hat', id:1},{type: 'big_hat', id:2}],
    },
    'big_hats': [
      {
        id: 1,
        type: "BigHat"
      },
      {
        id: 2,
        type: "BigHat"
      }
    ]
  }
```

So mapFind will be removed since its already mapped.

Maybe there is a way to use a method like afterBuild or afterFind or convertJsonAfterFind ?  to convert the json to something you want?  rather than mapFind ?? 
 
any thoughts? questions comments ?  before I change this?
