### ISSUE TITLE
define failing on merge

### ISSUE THREAD

**Issue by rtm** [danielspaniel/ember-data-factory-guy#67]
On this line: https://github.com/danielspaniel/ember-data-factory-guy/blob/master/dist/ember-data-factory-guy.js#L221

it calls merge, but I cannot figure out why merge would be defined here on the model definition, and in fact I am getting an undefined function error on this line.

**Comment by danielspaniel** [comment]
Yikes @rtm  .. you must be defining the model twice, which is why your getting this error. 
 My original intent was to merge the two definitions, but I never actually finished the merge funciton, so this is my mistake.  Thanks for pointing this out.  Can you find the place where you are defining the same model twice and fix that for now? 
 I will take this line out also and only put it back in when I finish the merge funciton.

**Comment by danielspaniel** [comment]
That code is fixed now, and will be pushed out in the next release.
