### ISSUE TITLE
Can't seem to use type as a property name

### ISSUE THREAD

**Issue by visoft** [danielspaniel/ember-data-factory-guy#92]
My model has a string property called `type`, however when using `make` and passing in `{ type: 'foo' }`, I get "Error: No model was found for 'foo'". Is there a workaround to this?

**Comment by danielspaniel** [comment]
ooo .. that is kind of a weak point.  I was hoping no one would use that as an attribute ( like with rails where they reserve that property name 'type' for use when using polymorphic models.  
 Do you have to use that property name?  Can you convince the database to change itself real quick? ( joking ) .. but if you can switch that .. it would be easiest ( duh ) .. because I can't think off the top of my head how I am going to change that internally.

**Comment by visoft** [comment]
I'll see what I can do about changing it. In the meantime hopefully you can come up with a solution :)

**Comment by danielspaniel** [comment]
@visoft ... there is a solution ( 99% sure ) , but it means you would flag that there are no polymorphic relationships on your models. where you can set a flag in the test environment that looks something like ENV.APP.FACTORY_GUY_NO_POLYMORPHIC_MODELS =  true
  to disable that use of the type field in FactoryGuy to determine the type of a model.

Let me know if that would work for you.

**Comment by visoft** [comment]
That would work awesome.

**Comment by danielspaniel** [comment]
Version 1.1.0 fixes this issue, and no funny business needed ( ENV.APP.FACTORY_GUY_NO_POLYMORPHIC_MODELS ) just works as is. Thanks for pushing me to fix this @visoft , because it showed me a flaw in my model definitions.
